version: 1

update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
    default_reviewers: ["cetinajero"]
    default_labels:
      - dependencies
      - python
